### Test DB connection
GET http://localhost:3000/test-db

### Login
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "password"
}

### Search 
GET http://localhost:3000/api/menus/search?q=PRIME
Cookie: authToken=valid-user-token

### Get Paginated menus 
GET http://localhost:3000/api/menus/paginated?page=1&limit=2
Cookie: authToken=valid-user-token

### Health Check
GET http://localhost:3000/api/dbHealth

### Get all menus
GET http://localhost:3000/api/menus

### Get tree
GET http://localhost:3000/api/menus/tree

### Create a new menu
POST http://localhost:3000/api/menus
Content-Type: application/json

{
  "menuid": 11,
  "menuname": "Prime_settings",
  "menucode": "BL_PM_STG",
  "parentmenuid": 8
}

### Update menu
PATCH  http://localhost:3000/api/menus/10
Content-Type: application/json

{
  "menucode": "BL_MN_MTN",
  "menuname" : "Menu Maintenance"
}

### Delete menu
DELETE http://localhost:3000/api/menus/1